FROM node:18-alpine

# 作業ディレクトリを設定
WORKDIR /usr/src/app

# Next.js のテレメトリ機能を無効化
ENV NEXT_TELEMETRY_DISABLED 1

# COPY package*.json ./
# RUN npm install
# COPY . .
# RUN npm run build

# # アプリケーションを起動
CMD ["npm", "run", "start"]
