services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: app_development
      MYSQL_USER: app_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-db:/var/lib/mysql
    
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rails-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
      
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs-frontend
    ports:
      - "8000:3000"
    volumes:
      - ./frontend/app:/usr/src/app
    command: "npm run dev"

volumes:
  mysql-db:
    driver: local
